config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'static_pages#home', as: 'home'
  resources :menuorders
  # resources :orders
  resources :reviews
  resources :food_items
  resources :restaurants
  resources :users
  #resources: checkout, only: [:create]
  get '/guide', to: 'static_pages#guide', as: 'guide'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/analytics', to: 'static_pages#analytics', as: 'analytics'
  get '/cart', to: 'cart#show', as: 'cart'
  patch '/cart', to: 'cart#update', as: 'edit_cart'
  post '/orders', to: 'orders#create', as: 'orders'
  get '/orders/:id', to: 'orders#show', as: 'order'
  get '/orders', to: 'orders#index'
  get '/restaurants/:id/reviews', to: 'restaurants#restaurant_reviews', as: 'restaurant_reviews'
  get '/users/:id/orders', to: 'users#orders', as: 'user_orders'
  get '/users/:id/reviews', to: 'users#reviews', as: 'user_reviews'
  get 'guide/bagels', to: 'guides#bagels', as: 'bagel'
  get 'guide/chinese', to: 'guides#chinese', as: 'chinese'
  get 'guide/greek', to: 'guides#greek', as: 'greek'
  get 'guide/health', to: 'guides#health', as: 'health'
  get 'guide/italian', to: 'guides#italian', as: 'italian'
  get 'guide/mexican', to: 'guides#mexican', as: 'mexican'
  get 'guide/american', to: 'guides#american', as: 'american'
  get 'guide/thai', to: 'guides#thai', as: 'thai'
  get 'admin/export/:id', to: 'admin/user#export'
  get 'admin/export_json/:id', to: 'admin/user#export_json'
  namespace :admin do
    resources :user
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  post 'checkout/create', to: 'checkout#create'
      
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authorized
  helper_method :current_user
  def home
  end

  def about
  end

  def contact
  end

  def guide
  end

  def analytics
    render :layout => 'indices'
  end  

  def current_user
    p session[:user_id]
    User.find_by( {id: session[:user_id]})
  end

end

app/views/static_pages/about.html.erb
<div class="container">
  <div class="row">
      <div class="info-box">
        <h2 class="center">About Us.</h2>
        <br>
        <p>
          Seamful is a project application developed by Sokolov Vladislav
        </p>


      </div>
  </div>
  <div class="empty-fill">
  </div>
</div>

app/views/static_pages/analytics.erb
<h1>Seamful Analytics</h1>

<br>
<h3>Number of Current Users:</h3>
<%= User.num_current_users %>
<br>
<br>
<h3>Most Active User:</h3>
<%= Order.most_active_user.fullname %>
<br>
<br>
<h3>Most Reviews Written: </h3>
<%= Review.most_reviews_by_user.fullname %>
<br>
<br>
<h3>Most Recently Registered User:</h3>
<%= User.newest.fullname %>
<br>
<br>
<h3>Most Popular / Most Ordered Restaurant:</h3>
<%= Order.most_ordered.name %>
<br>
<br>
<h3>Highest Average Rating: </h3>
<%= Restaurant.highest_avg_rating.name %> -
<%= Restaurant.highest_avg_rating.avg_rating %>
<br>
<br>
<h3>Lowest Average Rating</h3>
<%= Restaurant.lowest_avg_rating.name %> -
<%= Restaurant.lowest_avg_rating.avg_rating %>
<br>
<br>
<h3>Most Popular Dish</h3>
<%= Menuorder.most_popular_dish.food_name %>
<br>
<br>
<h3>Least Popular Dish</h3>
<%= Menuorder.least_popular_dish.food_name %>
<br>
<br>
<h3>Most Expensive Dish</h3>
<%= FoodItem.most_expensive.food_name %>
<br>
<br>
<h3>Most Expensive Order</h3>
<%= Order.most_expensive.id %> -
<%= Order.most_expensive.user.fullname %>
<br>
<br>
<h3>Restaurant Revenues</h3>
<% Restaurant.all.each do |restaurant| %>
  <br><h5><%= restaurant.name %><h5>
    $<%=restaurant.revenue%><br>
  <% end %>
<br>
<br>
<h3>Total User Spend</h3>
$<%= Order.total_spend %>

app/views/static_pages/contact.html.erb
<div class="container">
  <div class="row">
      <div class="info-box">
        <h2 class="center">Contact Us.</h2>
        <br>
        <p>
          For questions about your order, call 212-867-5309. For all other inqueries,
          email help@seamful.com, or call 212-867-5310. Thank you for choosing Seamful!
        </p>


      </div>
  </div>
  <div class="empty-fill">
  </div>
</div>

app/views/static_pages/guide.html.erb
<h1 class="guide" style="margin: 25px 0 0 0 ">Choose a Cuisine</h1>
<br>
  <div class="cuisine-select">
    <div class="cuisine"><%= link_to image_tag('Bagels.png'), bagel_path  %></div>
    <div class="cuisine"><%= link_to image_tag('Chinese.png'), chinese_path  %></div>
    <div class="cuisine"><%= link_to image_tag('Health.png'), health_path  %></div>
    <div class="cuisine"><%= link_to image_tag('Greek.png'), greek_path  %></div>
    <div class="cuisine"><%= link_to image_tag('All.png'), restaurants_path  %></div>
    <div class="cuisine"><%= link_to image_tag('Italian.png'), italian_path  %></div>
    <div class="cuisine"><%= link_to image_tag('Mexican.png'), mexican_path  %></div>
    <div class="cuisine"><%= link_to image_tag('New_American.png'), american_path  %></div>
    <div class="cuisine"><%= link_to image_tag('Thai.png'), thai_path  %></div>
  </div>

  <br>
  <br>
  <br>

app/views/static_pages/home.html.erb
<div class="home">
  <div class="flex-container">
      <div>
        <h3 style="margin: 40vh 0 0 0; color: white; font-family:'Pacifico', cursive; text-shadow: -1px 0 grey, -1px grey, 1px grey; font-size: 50px"> Welcome</h3>
      </div>
  </div>

  <div class="flex-container two" style="margin: -2vh 0 0 0;">
    <div>
    <% if session[:user_id] == nil %>
      <%=link_to "Become A Member", new_user_path, class: "btn btn-success"%>
    <% end %>
    <% if current_user %>
    You are logged in
    <% end %>
    </div>
    <div>
      <% if session[:user_id] == nil %>
        <%= link_to "Existing Customer", login_path, class: "btn btn-info" %>
      <% else %>
        <%= link_to "Existing Customer", guide_path, class: "btn btn-info" %>
      <% end %>
    </div>
</div>
</div>

<div class="grad empty-fill">
</div>