config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'static_pages#home', as: 'home'
  resources :menuorders
  # resources :orders
  resources :reviews
  resources :food_items
  resources :restaurants
  resources :users
  #resources: checkout, only: [:create]
  get '/guide', to: 'static_pages#guide', as: 'guide'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/analytics', to: 'static_pages#analytics', as: 'analytics'
  get '/cart', to: 'cart#show', as: 'cart'
  patch '/cart', to: 'cart#update', as: 'edit_cart'
  post '/orders', to: 'orders#create', as: 'orders'
  get '/orders/:id', to: 'orders#show', as: 'order'
  get '/orders', to: 'orders#index'
  get '/restaurants/:id/reviews', to: 'restaurants#restaurant_reviews', as: 'restaurant_reviews'
  get '/users/:id/orders', to: 'users#orders', as: 'user_orders'
  get '/users/:id/reviews', to: 'users#reviews', as: 'user_reviews'
  get 'guide/bagels', to: 'guides#bagels', as: 'bagel'
  get 'guide/chinese', to: 'guides#chinese', as: 'chinese'
  get 'guide/greek', to: 'guides#greek', as: 'greek'
  get 'guide/health', to: 'guides#health', as: 'health'
  get 'guide/italian', to: 'guides#italian', as: 'italian'
  get 'guide/mexican', to: 'guides#mexican', as: 'mexican'
  get 'guide/american', to: 'guides#american', as: 'american'
  get 'guide/thai', to: 'guides#thai', as: 'thai'
  get 'admin/export/:id', to: 'admin/user#export'
  get 'admin/export_json/:id', to: 'admin/user#export_json'
  namespace :admin do
    resources :user
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  post 'checkout/create', to: 'checkout#create'
      
    
end

app/models/user.rb
class User < ApplicationRecord
  before_create :confirmation_token
  has_secure_password
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :restaurants, through: :orders
  validates :email, uniqueness: true, presence: true
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows english letters" }, :length => { :minimum => 3, :maximum => 20}
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows english letters" }, :length => { :minimum => 3, :maximum => 20}
  validates :city_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows english letters" }, :length => { :minimum => 4, :maximum => 25}
  validates :state, format: { with: /\A[a-zA-Z]+\z/, message: "only allows english letters" }, :length => { :minimum => 4, :maximum => 30}
  validates :zipcode, presence: true, :numericality => true, :length => { :minimum => 6, :maximum => 8}
  validates :credit_card_num, :numericality => true, :length => { :minimum => 6, :maximum => 120}
  validates :phone_num, presence: true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }


  def fullname
    "#{self.first_name} #{self.last_name}"
  end

  def self.num_current_users
    User.all.count
  end

  def self.newest
    last
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private
  def confirmation_token
      if self.confirm_token.blank?
         self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
  end

end #END USER CLASS

app/controllers/admin/user_controller.rb
class Admin::UserController < Admin::BaseController
    before_action :set_user, only: [:show, :edit, :update, :destroy, :orders, :reviews]
    before_action :check_for_admin
    def index
        @users = User.all
        render :index
    end

    def show
        render :show
    end

    def check_for_admin
        redirect_to root_path, alert: "You dont have access" unless current_user.try(:admin?)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def destroy
          @user.destroy
          flash[:notice] = "Account for #{@user.first_name} deleted."
          redirect_to admin_user_index_path
    end

    def update
        if @user.update(user_params)
            @user.update(admin:true) if params["admin"] == "1"
            @user.update(admin:false) unless params["admin"] == "1"
          flash[:notice] = "Profile updated!"
          redirect_to admin_user_path
        else
          render :edit
        end
    end

    def edit
          render :edit
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :street_name, :city_name, :zipcode, :state, :credit_card_num, :phone_num)
    end

    def export
        @user = User.find(params["id"])
        respond_to :docx, :xlsx
        respond_to do |format|
          format.docx do
            render docx: 'export', filename: "#{@user.first_name}.docx"
          end
          format.xlsx do
            render xlsx: 'export', filename: "#{@user.first_name}"
          end
        end
    end
    
    def export_json
        @user = User.find(params["id"])
        file = File.write(Rails.root.join('app', 'assets', 'files', "#{@user.first_name}.json"), @user.to_json)
        send_data(@user.to_json, filename: "#{@user.first_name}.json", type: :json, disposition: "attachment",)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :confirm_email]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :orders, :reviews]

  def index
    @users = User.all
    render :index
  end

  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    @user.first_name = user_params[:first_name].titleize
    @user.last_name = user_params[:last_name].titleize
    @user.street_name = user_params[:street_name].titleize
    @user.city_name = user_params[:city_name].titleize
    @user.state = user_params[:state].titleize
    if @user.save
      #session[:user_id] = @user.id
      UserMailer.registration_confirmation(@user).deliver
      #flash[:notice] = "Please confirm your email address to continue"
      #flash.keep
      redirect_to home_path, notice:"Please confirm your email address to continue"
    else
      #flash[:notice] = "Ooooppss, something went wrong!"
      render :new, notice: "Ooooppss, something went wrong!" 
    end
  end

  def confirm_email
    @user = User.find_by_confirm_token(params[:id])
    if @user
      @user.email_activate
      #flash[:notice] = "Welcome to the Sample App! Your email has been confirmed.Please sign in to continue."
      #flash.keep
      redirect_to login_path, notice:"Welcome to the Sample App! Your email has been confirmed.Please sign in to continue."
    else
      #flash[:notice] = "Sorry. User does not exist"
      redirect_to home_path, notice:"Sorry. User does not exist"
    end
end

  def edit
    if current_user.id == @user.id
      render :edit
    else
      flash[:notice] = "You are not authorized to do that"
      redirect_to user_path(@user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @user.id
      @user.destroy
      session.destroy
      flash[:notice] = "Account for #{@user.first_name} deleted."
      redirect_to home_path
    else
      flash[:notice] = "You are not authorized to do that"
      redirect_to user_path(@user)
    end
  end

  def orders
    @orders = Order.where(user: @user)
  end

  def reviews
    @reviews = Review.where(user: @user)
  end

  def recommendations
  end

  

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :street_name, :city_name, :zipcode, :state, :credit_card_num, :phone_num, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/user/_form1.html.erb



<%= form_for @user, url: "/admin/user/#{@user.id}", method: :put do |f| %>

 <ol>
     <% @user.errors.full_messages.each do |msg| %>
       <strong><%= msg %></strong><br>
     <% end %>
   </ol>
 <div style="margin: 0 0 15px 2px"><%= f.text_field :first_name, placeholder: "First Name" ,size: 15%><text> </text>
<%= f.text_field :last_name,placeholder: "Last Name", size: 16 %></div>
<div>  <%= f.text_field :street_name ,placeholder: "Street Name",size: 33%></div>
<div>  <%= f.text_field :city_name, placeholder: "City Name",size: 33, height: 10 %> </div>
<div>  <%= f.text_field :state, placeholder: "State",size: 15%>
 <%= f.text_field :zipcode, placeholder: "Zipcode",size: 16%></div>
<div>  <%= f.telephone_field :phone_num, placeholder: "Phone Number",size: 33 %></div>
<div>  <%= f.text_field :credit_card_num, placeholder: "Credit Card Number",size: 33 %></div>
Admin?    : <%= check_box_tag :admin, "1", @user.admin %>
<br>
 <%= f.submit class: "btn btn-success"%>
 <% end %>

</div>


app/views/admin/user/edit.html.erb
<div class="account">
  <div class="flex-container">


    <h3 style="margin: 20px 0 0 0; color: white; font-family:'Pacifico', cursive; text-shadow: -1px 0 grey, -1px grey, 1px grey; font-size: 50px;">Edit Account</h3>
  </div>
  <div class="flex-container account1 gradi">
      <%= render partial: 'form1' %>
  </div>


</div>

app/views/admin/user/export.docx.erb
<html>
  <head>
  </head>
    <body>
      <h2><strong>User information:</strong></h2>
      <p>Fullname: <%= @user.fullname %><br></p>
      <p>Street Name: <%= @user.street_name %><br></p>
      <p>City Name: <%= @user.city_name%><br></p>
      <p>Zipcode: <%= @user.zipcode%><br></p>
      <p>Phone Number: <%= @user.phone_num %><br></p>
      <p>Credit Card: <%= @user.credit_card_num %><br></p>
      <p>Email: <%= @user.email %><br></p>
      <% if @user.admin %>
     <p>Admin: true</p>
     <% else %>
     <p>Admin: false</p>
     <% end %>
    </body>
</html>

app/views/admin/user/index.html.erb
<h1>Seamful Users</h1>

<div class="user1">
<ul>
<% @users.each do |user| %>
  <li><%=link_to user.first_name, admin_user_path(user) %></li>
<% end %>
</ul>
</div>

app/views/admin/user/show.html.erb
<div class="user">
   <div class="flex-container">
       <h3 style="margin: 20px 0 0 0; color: white; font-family:'Pacifico', cursive; text-shadow: -1px 0 grey, -1px grey, 1px grey; font-size: 50px"> <%= @user.fullname %></h3>
   </div>
   <div class="flex-container link">
           <div><%= link_to "Order History", user_orders_path,class: 'link-to-text-color' %></div>
           <div><%= link_to "See all reviews", user_reviews_path,class: 'link-to-text-color' %></div>
         <br>
       <br>
     <br>
   </div>
 <div class="flex-container info">
     <p><%= @user.fullname %><br>
     <%= @user.street_name %><br>
     <%= @user.city_name%><br>
     <%= @user.zipcode%><br>
     <%= @user.phone_num %><br>
     <%= @user.credit_card_num %><br>
     <%= @user.email %><br>
     <%= @user.password %><br>
     <% if @user.admin %>
     admin:true
     <% else %>
     admin:false
     <% end %>
     </p>
  </div>
     <br>
      <div class="flex-container button1">
        <div><%= link_to "Update Information", edit_admin_user_path(@user), class: "btn btn-info"%></div>
        <div><%= button_to "Delete Account", admin_user_path(@user), {method: :delete, class: "btn btn-info"}%></div>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                  Export
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                  <li>
                      <%= 
                          link_to 'EXPORT JSON',
                                  "/admin/export_json/#{@user.id}",
                                  data: {method: :get},
                                  class: "btn"
                        %>
                    </li>
                    <li>
                      <%= 
                        link_to 'EXPORT EXCEL',
                                "/admin/export/#{@user.id}.xlsx",
                                data: {method: :get},
                                class: "btn",
                                target: "_blank"

                      %>
                    </li>
                    <li>
                      <%= 
                        link_to 'EXPORT WORD',
                                "/admin/export/#{@user.id}.docx",
                                data: {method: :get},
                                class: "btn",
                                target: "_blank"

                      %>
                    </li>
                </ul>
      </div>
 <br>
</div>