config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'static_pages#home', as: 'home'
  resources :menuorders
  # resources :orders
  resources :reviews
  resources :food_items
  resources :restaurants
  resources :users
  #resources: checkout, only: [:create]
  get '/guide', to: 'static_pages#guide', as: 'guide'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/analytics', to: 'static_pages#analytics', as: 'analytics'
  get '/cart', to: 'cart#show', as: 'cart'
  patch '/cart', to: 'cart#update', as: 'edit_cart'
  post '/orders', to: 'orders#create', as: 'orders'
  get '/orders/:id', to: 'orders#show', as: 'order'
  get '/orders', to: 'orders#index'
  get '/restaurants/:id/reviews', to: 'restaurants#restaurant_reviews', as: 'restaurant_reviews'
  get '/users/:id/orders', to: 'users#orders', as: 'user_orders'
  get '/users/:id/reviews', to: 'users#reviews', as: 'user_reviews'
  get 'guide/bagels', to: 'guides#bagels', as: 'bagel'
  get 'guide/chinese', to: 'guides#chinese', as: 'chinese'
  get 'guide/greek', to: 'guides#greek', as: 'greek'
  get 'guide/health', to: 'guides#health', as: 'health'
  get 'guide/italian', to: 'guides#italian', as: 'italian'
  get 'guide/mexican', to: 'guides#mexican', as: 'mexican'
  get 'guide/american', to: 'guides#american', as: 'american'
  get 'guide/thai', to: 'guides#thai', as: 'thai'
  get 'admin/export/:id', to: 'admin/user#export'
  get 'admin/export_json/:id', to: 'admin/user#export_json'
  namespace :admin do
    resources :user
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  post 'checkout/create', to: 'checkout#create'
      
    
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :food_items
  has_many :orders
  has_many :reviews
  has_many :users, through: :orders


  def menu_category(cat)
    self.food_items.where(category: cat)
  end

  def get_avg
    if self.reviews.count != 0
      (self.reviews.sum(:rating).to_f/self.reviews.count).round(2)
    else
      0
    end
  end

  def stars
    rating = self.get_avg #3.6
    whole_star = '<i class="fas fa-star"></i>'
    half_star = '<i class="fas fa-star-half"></i>'
    stars = ""
    # whole_stars = (rating / 1).floor
    # half_star = 0
    # decimal_stars = rating % 1 # .6
    #
    # if decimal_stars >= 0.8
    #   whole_stars += 1
    # elsif decimal_stars >= 0.3
    #   half_star = 1
    # end

    until rating < 1
      stars << whole_star
      rating -= 1
    end

    if rating <= 0.8
      stars << whole_star
    else
      stars << half_star
    end

    stars

  end

  def avg_rating
    if self.reviews.sum(:rating) != 0
      avg = (self.reviews.sum(:rating).to_f/self.reviews.count).round(2)
      "#{avg} stars"
    else
      return "There are not enough reviews for this restaurant."
    end
  end

  def self.highest_avg_rating
    Restaurant.all.sort_by { |a| a.get_avg }.last
  end

  def self.lowest_avg_rating
    Restaurant.all.sort_by { |a| a.get_avg }.first
  end

  def revenue
    self.orders.sum(&:total)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :restaurant_reviews]

  def index
    @restaurants = Restaurant.all.sort_by{|restaurant| restaurant.name }
  end

  def show
    render :layout => 'indices'
  end

  def restaurant_reviews
    @reviews = Review.all.select do |review|
      review.restaurant.id == @restaurant.id
    end
  end


private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :street_name, :city_name, :zipcode, :state, :phone_num, :cuisine, :price_range)
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/index.erb
<div class="restaurant_background">
<h1 style="color:white; padding: 15px">  Seamful Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
  <li class="list-group-item"><%= link_to restaurant.name, restaurant_path(restaurant), class:'link-to-text-color' %></li>
  <% end %>
</ul>
<br>
<br>
</div>

app/views/restaurants/restaurant_reviews.erb
<h1>Reviews for <%= @restaurant.name %></h1>
<div class="restaurant_background1">
<div class=amazing-reviews>
  <% @reviews.each do |review| %>
  <blockquote>
    <header>
      <span data-rating=5>
        <% review.rating.times do |rating| %>⭐️<% end %>
      </span>
      <span>, <%= review.created_at.strftime("%B %d %Y") %></span>
      <span>By <em><%= review.user.fullname %></em></span>
    </header>
    <p><%= review.content %></p>
  </blockquote>
  <% end %>
</div>
</div>

app/views/restaurants/show.erb
<%= link_to "Back", guide_path, class: 'link-to-text-color' %>
<br>
<br>
<h4><%= @restaurant.name %></h4>
<% @restaurant.get_avg.floor.times do %><i class="fas fa-star"></i><%end%>
<%if @restaurant.get_avg%1 <= 0.8 && @restaurant.get_avg%1 >=0.3%>
  <i class="fas fa-star-half"></i>
  <% elsif @restaurant.get_avg%1 >0.8 %>
    <i class="fas fa-star"></i>
  <% end %>(<%= @restaurant.get_avg %>)<br>
<%= @restaurant.street_name %><br>
<%= @restaurant.city_name %>, <%= @restaurant.state %> <%= @restaurant.zipcode %><br>
<%= @restaurant.phone_num %><br>
<%= link_to "See all reviews", restaurant_reviews_path, class: 'link-to-text-color' %>
<br>
<%= link_to "Write a Review", new_review_path, class: 'link-to-text-color' %>



<%= form_tag edit_cart_path, method: :patch do  %>
<input name="restaurant_id" value="<%= @restaurant.id %>" type="hidden" />

<br>
<div class="container">

  <h5>Drinks</h5>
  <div class="container">
    <div class="row">
      <% if @restaurant.menu_category("Drinks") == []%>
        <p class="unavailable">There are no drinks for this menu.</p>
      <% else %>
      <% @restaurant.menu_category("Drinks").each do |item| %>
      <div class="col-md-6 food-border">
        <h6><%= item.food_name %><h6>
          <p class="price"> $<%= item.price %></p>
          <% unless item.picture_url.nil? %>
        <%= image_tag(asset_path(item.picture_url), class: "container") %>
      <% end %>
          <p class="description"><em><%= item.description %></em><p>
            Quantity: <input type="number" name="items[<%= item.id %>]" min="0" step="1" max="100">
      </div>
      <% end %>
    <% end %>
</div>
</div>



<h5>Appetizers</h5>
<div class="container">
  <div class="row">
    <% if @restaurant.menu_category("Appetizers") == []%>
      <p class="unavailable">There are no appetizers for this menu.</p>
    <% else %>
    <% @restaurant.menu_category("Appetizers").each do |item| %>
    <div class="col-md-6 food-border">
      <h6><%= item.food_name %><h6>
        <p class="price"> $<%= item.price %></p>
        <% unless item.picture_url.nil? %>
        <%= image_tag(asset_path(item.picture_url), class: "container") %>
      <% end %>
        <p class="description"><em><%= item.description %></em><p>
          Quantity: <input type="number" name="items[<%= item.id %>]" min="0" step="1" max="100">
    </div>
    <% end %>
  <% end %>
  </div>
</div>


<h5>Mains</h5>
<div class="container">
  <div class="row">
    <% if @restaurant.menu_category("Mains") == []%>
      <p class="unavailable">There are no main dishes for this menu.</p>
    <% else %>
    <% @restaurant.menu_category("Mains").each do |item| %>
    <div class="col-md-6 food-border">
      <h6><%= item.food_name %><h6>
      <p class="price"> $<%= item.price %></p>
      <% unless item.picture_url.nil? %>
        <%= image_tag(asset_path(item.picture_url), class: "container") %>
      <% end %>
        <p class="description"><em><%= item.description %></em><p>
          Quantity: <input type="number" name="items[<%= item.id %>]" min="0" step="1" max="100">
    </div>
    <% end %>
  <% end %>
  </div>
</div>

<h5>Desserts</h5>
<div class="container">
  <div class="row">
    <% if @restaurant.menu_category("Desserts") == []%>
    <p class="unavailable">There are no desserts for this menu.</p>
    <% else %>
    <% @restaurant.menu_category("Desserts").each do |item| %>
    <div class="col-md-6 food-border">
      <h6><%= item.food_name %><h6>
        <p class="price"> $<%= item.price %></p>
        <% unless item.picture_url.nil? %>
        <%= image_tag(asset_path(item.picture_url), class: "container") %>
      <% end %>
        <p class="description"><em><%= item.description %></em><p>
          Quantity: <input type="number" name="items[<%= item.id %>]" min="0" step="1" max="100">
    </div>
    <% end %>
  <% end %>
  </div>
</div>
<div ALIGN=CENTER><%= submit_tag "Add to Cart", class: "btn btn-primary" %></div>
<% end %>